apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-dep
   labels:
      app: {{ .Values.application }}
      env: dev
spec:
<<<<<<< HEAD
   replicas: 6
=======
   replicas: 5
>>>>>>> 5f132d83d3a5f0f2776602cf6410d36a178bfe04
   selector:
      matchLabels:
         app: {{ .Values.application }}
   template:
      metadata:
         labels:
            app: {{ .Values.application }}
      spec:
         containers:
         - name: nginx
           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
