apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-dep
   labels:
      app: {{ .Values.application }}
      env: dev
spec:
   replicas: 6
   selector:
      matchLabels:
         app: {{ .Values.application }}
   template:
      metadata:
         labels:
            app: {{ .Values.application }}
      spec:
         containers:
         - name: nginx
           image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
